export interface CountryIsoCode {
    countryISO2Code: string;
    country: string;
}

export const isoReference: CountryIsoCode[] = [
    { countryISO2Code:'AD',country:'Andorra' },
    { countryISO2Code:'AE',country:'United Arab Emirates' },
    { countryISO2Code:'AF',country:'Afghanistan' },
    { countryISO2Code:'AG',country:'Antigua and Barbuda' },
    { countryISO2Code:'AI',country:'Anguilla' },
    { countryISO2Code:'AL',country:'Albania' },
    { countryISO2Code:'AM',country:'Armenia' },
    { countryISO2Code:'AO',country:'Angola' },
    { countryISO2Code:'AQ',country:'Antarctica' },
    { countryISO2Code:'AR',country:'Argentina' },
    { countryISO2Code:'AS',country:'American Samoa' },
    { countryISO2Code:'AT',country:'Austria' },
    { countryISO2Code:'AU',country:'Australia' },
    { countryISO2Code:'AW',country:'Aruba' },
    { countryISO2Code:'AX',country:'Åland Islands' },
    { countryISO2Code:'AZ',country:'Azerbaijan' },
    { countryISO2Code:'BA',country:'Bosnia and Herzegovina' },
    { countryISO2Code:'BB',country:'Barbados' },
    { countryISO2Code:'BD',country:'Bangladesh' },
    { countryISO2Code:'BE',country:'Belgium' },
    { countryISO2Code:'BF',country:'Burkina Faso' },
    { countryISO2Code:'BG',country:'Bulgaria' },
    { countryISO2Code:'BH',country:'Bahrain' },
    { countryISO2Code:'BI',country:'Burundi' },
    { countryISO2Code:'BJ',country:'Benin' },
    { countryISO2Code:'BL',country:'Saint Barthélemy' },
    { countryISO2Code:'BM',country:'Bermuda' },
    { countryISO2Code:'BN',country:'Brunei Darussalam' },
    { countryISO2Code:'BO',country:'Bolivia (Plurinational State of)' },
    { countryISO2Code:'BQ',country:'Bonaire, Sint Eustatius and Saba' },
    { countryISO2Code:'BR',country:'Brazil' },
    { countryISO2Code:'BS',country:'Bahamas' },
    { countryISO2Code:'BT',country:'Bhutan' },
    { countryISO2Code:'BV',country:'Bouvet Island' },
    { countryISO2Code:'BW',country:'Botswana' },
    { countryISO2Code:'BY',country:'Belarus' },
    { countryISO2Code:'BZ',country:'Belize' },
    { countryISO2Code:'CA',country:'Canada' },
    { countryISO2Code:'CC',country:'Cocos (Keeling) Islands' },
    { countryISO2Code:'CD',country:'Congo, Democratic Republic of the' },
    { countryISO2Code:'CF',country:'Central African Republic' },
    { countryISO2Code:'CH',country:'Switzerland' },
    { countryISO2Code:'CI',country:'Côte d\'Ivoire' },
    { countryISO2Code:'CK',country:'Cook Islands' },
    { countryISO2Code:'CL',country:'Chile' },
    { countryISO2Code:'CM',country:'Cameroon' },
    { countryISO2Code:'CN',country:'China' },
    { countryISO2Code:'CO',country:'Colombia' },
    { countryISO2Code:'CR',country:'Costa Rica' },
    { countryISO2Code:'CU',country:'Cuba' },
    { countryISO2Code:'CV',country:'Cabo Verde' },
    { countryISO2Code:'CW',country:'Curaçao' },
    { countryISO2Code:'CX',country:'Christmas Island' },
    { countryISO2Code:'CY',country:'Cyprus' },
    { countryISO2Code:'CZ',country:'Czechia' },
    { countryISO2Code:'DE',country:'Germany' },
    { countryISO2Code:'DJ',country:'Djibouti' },
    { countryISO2Code:'DK',country:'Denmark' },
    { countryISO2Code:'DM',country:'Dominica' },
    { countryISO2Code:'DO',country:'Dominican Republic' },
    { countryISO2Code:'DZ',country:'Algeria' },
    { countryISO2Code:'EC',country:'Ecuador' },
    { countryISO2Code:'EE',country:'Estonia' },
    { countryISO2Code:'EG',country:'Egypt' },
    { countryISO2Code:'EH',country:'Western Sahara' },
    { countryISO2Code:'ER',country:'Eritrea' },
    { countryISO2Code:'ES',country:'Spain' },
    { countryISO2Code:'ET',country:'Ethiopia' },
    { countryISO2Code:'FI',country:'Finland' },
    { countryISO2Code:'FJ',country:'Fiji' },
    { countryISO2Code:'FK',country:'Falkland Islands' },
    { countryISO2Code:'FM',country:'Micronesia (Federated States of)' },
    { countryISO2Code:'FO',country:'Faroe Islands' },
    { countryISO2Code:'FR',country:'France' },
    { countryISO2Code:'GA',country:'Gabon' },
    { countryISO2Code:'GB',country:'United Kingdom of Great Britain and Northern Ireland' },
    { countryISO2Code:'GD',country:'Grenada' },
    { countryISO2Code:'GE',country:'Georgia' },
    { countryISO2Code:'GF',country:'French Guiana' },
    { countryISO2Code:'GG',country:'Guernsey' },
    { countryISO2Code:'GH',country:'Ghana' },
    { countryISO2Code:'GI',country:'Gibraltar' },
    { countryISO2Code:'GL',country:'Greenland' },
    { countryISO2Code:'GM',country:'Gambia' },
    { countryISO2Code:'GN',country:'Guinea' },
    { countryISO2Code:'GP',country:'Guadeloupe' },
    { countryISO2Code:'GQ',country:'Equatorial Guinea' },
    { countryISO2Code:'GR',country:'Greece' },
    { countryISO2Code:'GS',country:'South Georgia and the South Sandwich Islands' },
    { countryISO2Code:'GT',country:'Guatemala' },
    { countryISO2Code:'GU',country:'Guam' },
    { countryISO2Code:'GW',country:'Guinea-Bissau' },
    { countryISO2Code:'GY',country:'Guyana' },
    { countryISO2Code:'HK',country:'Hong Kong' },
    { countryISO2Code:'HM',country:'Heard Island and McDonald Islands' },
    { countryISO2Code:'HN',country:'Honduras' },
    { countryISO2Code:'HR',country:'Croatia' },
    { countryISO2Code:'HT',country:'Haiti' },
    { countryISO2Code:'HU',country:'Hungary' },
    { countryISO2Code:'ID',country:'Indonesia' },
    { countryISO2Code:'IE',country:'Ireland' },
    { countryISO2Code:'IL',country:'Israel' },
    { countryISO2Code:'IM',country:'Isle of Man' },
    { countryISO2Code:'IN',country:'India' },
    { countryISO2Code:'IO',country:'British Indian Ocean Territory' },
    { countryISO2Code:'IQ',country:'Iraq' },
    { countryISO2Code:'IR',country:'Iran (Islamic Republic of)' },
    { countryISO2Code:'IS',country:'Iceland' },
    { countryISO2Code:'IT',country:'Italy' },
    { countryISO2Code:'JE',country:'Jersey' },
    { countryISO2Code:'JM',country:'Jamaica' },
    { countryISO2Code:'JO',country:'Jordan' },
    { countryISO2Code:'JP',country:'Japan' },
    { countryISO2Code:'KE',country:'Kenya' },
    { countryISO2Code:'KG',country:'Kyrgyzstan' },
    { countryISO2Code:'KH',country:'Cambodia' },
    { countryISO2Code:'KI',country:'Kiribati' },
    { countryISO2Code:'KM',country:'Comoros' },
    { countryISO2Code:'KN',country:'Saint Kitts and Nevis' },
    { countryISO2Code:'KP',country:'North Korea (Democratic People\'s Republic of)' },
    { countryISO2Code:'KR',country:'South Korea, Republic of' },
    { countryISO2Code:'KW',country:'Kuwait' },
    { countryISO2Code:'KY',country:'Cayman Islands' },
    { countryISO2Code:'KZ',country:'Kazakhstan' },
    { countryISO2Code:'LA',country:'Lao People\'s Democratic Republic' },
    { countryISO2Code:'LB',country:'Lebanon' },
    { countryISO2Code:'LC',country:'Saint Lucia' },
    { countryISO2Code:'LI',country:'Liechtenstein' },
    { countryISO2Code:'LK',country:'Sri Lanka' },
    { countryISO2Code:'LR',country:'Liberia' },
    { countryISO2Code:'LS',country:'Lesotho' },
    { countryISO2Code:'LT',country:'Lithuania' },
    { countryISO2Code:'LU',country:'Luxembourg' },
    { countryISO2Code:'LV',country:'Latvia' },
    { countryISO2Code:'LY',country:'Libya' },
    { countryISO2Code:'MA',country:'Morocco' },
    { countryISO2Code:'MC',country:'Monaco' },
    { countryISO2Code:'MD',country:'Moldova, Republic of' },
    { countryISO2Code:'ME',country:'Montenegro' },
    { countryISO2Code:'MF',country:'Saint Martin (French part)' },
    { countryISO2Code:'MG',country:'Madagascar' },
    { countryISO2Code:'MH',country:'Marshall Islands' },
    { countryISO2Code:'MK',country:'North Macedonia' },
    { countryISO2Code:'ML',country:'Mali' },
    { countryISO2Code:'MM',country:'Myanmar' },
    { countryISO2Code:'MN',country:'Mongolia' },
    { countryISO2Code:'MO',country:'Macao' },
    { countryISO2Code:'MP',country:'Northern Mariana Islands' },
    { countryISO2Code:'MQ',country:'Martinique' },
    { countryISO2Code:'MR',country:'Mauritania' },
    { countryISO2Code:'MS',country:'Montserrat' },
    { countryISO2Code:'MT',country:'Malta' },
    { countryISO2Code:'MU',country:'Mauritius' },
    { countryISO2Code:'MV',country:'Maldives' },
    { countryISO2Code:'MW',country:'Malawi' },
    { countryISO2Code:'MX',country:'Mexico' },
    { countryISO2Code:'MY',country:'Malaysia' },
    { countryISO2Code:'MZ',country:'Mozambique' },
    { countryISO2Code:'NA',country:'Namibia' },
    { countryISO2Code:'NC',country:'New Caledonia' },
    { countryISO2Code:'NF',country:'Norfolk Island' },
    { countryISO2Code:'NG',country:'Nigeria' },
    { countryISO2Code:'NI',country:'Nicaragua' },
    { countryISO2Code:'NL',country:'Netherlands' },
    { countryISO2Code:'NO',country:'Norway' },
    { countryISO2Code:'NP',country:'Nepal' },
    { countryISO2Code:'NR',country:'Nauru' },
    { countryISO2Code:'NU',country:'Niue' },
    { countryISO2Code:'NZ',country:'New Zealand' },
    { countryISO2Code:'OM',country:'Oman' },
    { countryISO2Code:'PA',country:'Panama' },
    { countryISO2Code:'PE',country:'Peru' },
    { countryISO2Code:'PF',country:'French Polynesia' },
    { countryISO2Code:'PG',country:'Papua New Guinea' },
    { countryISO2Code:'PH',country:'Philippines' },
    { countryISO2Code:'PK',country:'Pakistan' },
    { countryISO2Code:'PL',country:'Poland' },
    { countryISO2Code:'PM',country:'Saint Pierre and Miquelon' },
    { countryISO2Code:'PN',country:'Pitcairn' },
    { countryISO2Code:'PR',country:'Puerto Rico' },
    { countryISO2Code:'PT',country:'Portugal' },
    { countryISO2Code:'PW',country:'Palau' },
    { countryISO2Code:'PY',country:'Paraguay' },
    { countryISO2Code:'QA',country:'Qatar' },
    { countryISO2Code:'RE',country:'Réunion' },
    { countryISO2Code:'RO',country:'Romania' },
    { countryISO2Code:'RS',country:'Serbia' },
    { countryISO2Code:'RU',country:'Russian Federation' },
    { countryISO2Code:'RW',country:'Rwanda' },
    { countryISO2Code:'SA',country:'Saudi Arabia' },
    { countryISO2Code:'SB',country:'Solomon Islands' },
    { countryISO2Code:'SC',country:'Seychelles' },
    { countryISO2Code:'SD',country:'Sudan' },
    { countryISO2Code:'SE',country:'Sweden' },
    { countryISO2Code:'SG',country:'Singapore' },
    { countryISO2Code:'SH',country:'Saint Helena, Ascension and Tristan da Cunha' },
    { countryISO2Code:'SI',country:'Slovenia' },
    { countryISO2Code:'SJ',country:'Svalbard and Jan Mayen' },
    { countryISO2Code:'SK',country:'Slovakia' },
    { countryISO2Code:'SL',country:'Sierra Leone' },
    { countryISO2Code:'SM',country:'San Marino' },
    { countryISO2Code:'SN',country:'Senegal' },
    { countryISO2Code:'SO',country:'Somalia' },
    { countryISO2Code:'SR',country:'Suriname' },
    { countryISO2Code:'SS',country:'South Sudan' },
    { countryISO2Code:'ST',country:'Sao Tome and Principe' },
    { countryISO2Code:'SV',country:'El Salvador' },
    { countryISO2Code:'SX',country:'Sint Maarten (Dutch part)' },
    { countryISO2Code:'SY',country:'Syrian Arab Republic' },
    { countryISO2Code:'SZ',country:'Eswatini' },
    { countryISO2Code:'TC',country:'Turks and Caicos Islands' },
    { countryISO2Code:'TD',country:'Chad' },
    { countryISO2Code:'TF',country:'French Southern Territories' },
    { countryISO2Code:'TG',country:'Togo' },
    { countryISO2Code:'TH',country:'Thailand' },
    { countryISO2Code:'TJ',country:'Tajikistan' },
    { countryISO2Code:'TK',country:'Tokelau' },
    { countryISO2Code:'TL',country:'Timor-Leste' },
    { countryISO2Code:'TM',country:'Turkmenistan' },
    { countryISO2Code:'TN',country:'Tunisia' },
    { countryISO2Code:'TO',country:'Tonga' },
    { countryISO2Code:'TR',country:'Turkey' },
    { countryISO2Code:'TT',country:'Trinidad and Tobago' },
    { countryISO2Code:'TV',country:'Tuvalu' },
    { countryISO2Code:'TW',country:'Taiwan' },
    { countryISO2Code:'TZ',country:'Tanzania, United Republic of' },
    { countryISO2Code:'UA',country:'Ukraine' },
    { countryISO2Code:'UG',country:'Uganda' },
    { countryISO2Code:'UM',country:'United States Minor Outlying Islands' },
    { countryISO2Code:'US',country:'United States of America' },
    { countryISO2Code:'UY',country:'Uruguay' },
    { countryISO2Code:'UZ',country:'Uzbekistan' },
    { countryISO2Code:'VA',country:'Holy See' },
    { countryISO2Code:'VC',country:'Saint Vincent and the Grenadines' },
    { countryISO2Code:'VE',country:'Venezuela (Bolivarian Republic of)' },
    { countryISO2Code:'VG',country:'Virgin Islands (British)' },
    { countryISO2Code:'VI',country:'Virgin Islands (U.S.)' },
    { countryISO2Code:'VN',country:'Viet Nam' },
    { countryISO2Code:'VU',country:'Vanuatu' },
    { countryISO2Code:'WF',country:'Wallis and Futuna' },
    { countryISO2Code:'WS',country:'Samoa' },
    { countryISO2Code:'YE',country:'Yemen' },
    { countryISO2Code:'YT',country:'Mayotte' },
    { countryISO2Code:'ZA',country:'South Africa' },
    { countryISO2Code:'ZM',country:'Zambia' },
    { countryISO2Code:'ZW',country:'Zimbabwe' }    
];